{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "setbeat-client.serviceAccountName" . }}
  labels:
  {{ include "setbeat-client.labels" . | nindent 4 }}
  {{- end -}}
